console.log("Welcom back chief");
var myName = "Saravanan";
console.log(myName);
var no1 = 12345, no2 = 123.45;
console.log(no1, no2);
var cond1 = true, cond2 = false;
console.log(cond1);
var course = ["React", "angular", "java"];
console.log(course);
var breakfast = ["idly", "dosa", "upma"];
console.log(breakfast);
var breakitem = [123, 4];
console.log(breakitem);
var item = ["somasa", 20];
console.log(item);
var days;
(function (days) {
    days[days["sun"] = 100] = "sun";
    days[days["mon"] = 101] = "mon";
    days[days["tue"] = 102] = "tue";
    days[days["wed"] = 103] = "wed";
    days[days["sat"] = 104] = "sat";
})(days || (days = {}));
;
var day1 = days.mon;
console.log(day1);
var information = "Changepond";
console.log(information);
var data = 1234;
console.log(data);
